Repository CAU-OSS-2023-Team15/Project-1, pull requests merged in 2023-05, with the labels that each got.

#6 [DOC] Convention 문서 구성
  Rules.md
Labels: documentation

#9 [DEV] 기초 레이아웃 구성 - 좌측 메뉴 제거
  assets/css/style.css
  src/index.html
Labels: dev

#10 [DEV] 기초 레이아웃 구성 - 상단 메뉴 구성
  preload.js
  src/index.html
  src/index.js
Labels: dev

#18 [FIX] 추가기능 구현 - 파일/폴더 삭제 버그 수정
  main.js
  preload.js
  src/confirm_delete.html
Labels: fix

#19 [DEV] VCS - Git Add / Restore / Remove / Move
  main.js
  preload.js
  src/git_rename_dialog.html
Labels: dev

#20 [FIX] 추가기능 구현 - 파일/폴더 생성 버그 수정
  main.js
  preload.js
Labels: fix

#25 [DEV] VCS - Git Initialization
  main.js
  preload.js
  src/index.html
Labels: dev

#28 [FIX] 불필요 UI 제거
  src/index.html
  src/index.js
Labels: fix

#27 [FIX] 파일관리 기능 안정화
  main.js
  preload.js
Labels: fix

#29 [DEV] VCS - Git Status
  preload.js
Labels: dev

#26 [FIX] VCS 작업 관련 추가적인 예외처리
  main.js
Labels: fix

#30 [FIX] VCS 관련 Refresh 적용
  main.js
  src/git_rename_dialog.html
Labels: fix

#32 [FIX] VCS Unstage 예외처리
  main.js
Labels: fix

#33 [DEV] 기본 파일관리 기능 작업
  main.js
  preload.js
  src/confirm_move.html
  src/find.html
  src/overwritemove.html
Labels: dev

#35 [DOC] Project README.md 문서
  README.md
  README_Assets/Proj1_1.png
  README_Assets/Proj1_2.png
  README_Assets/Proj1_3.png
  README_Assets/Proj1_4.png
  README_Assets/Proj1_5.png
  README_Assets/Proj1_6.png
Labels: documentation

#40 [DEV] VCS - Git Merge
  main.js
  preload.js
  src/git_merge_dialog.html
  src/git_merge_dialog_fail.html
  src/git_merge_dialog_success.html
  src/index.html
Labels: dev

#41 [DEV] VCS - Git Branch Management
  main.js
  preload.js
  src/git_branch_checkout_dialog.html
  src/git_branch_create_dialog.html
  src/git_branch_delete_dialog.html
  src/git_branch_rename_dialog.html
Labels: dev

#42 [FIX] VCS - Git Merge/msg_notifiy
  main.js
  preload.js
  src/git_merge_dialog_fail.html
  src/git_merge_dialog_success.html
Labels: fix
