Repository CAU-OSS-2023-Team15/Project-1, pull requests merged in 2023-06, with the labels that each got.

#44 [DEV] VCS - Github Clone
  main.js
  preload.js
  src/git_clone_dialog.html
  src/git_clone_visibility_dialog.html
  src/index.html
Labels: dev

#43 [DEV] VCS - Git Commit History
  main.js
  preload.js
  src/git_history.html
  src/git_history_status.html
  src/index.html
Labels: dev

#47 [FIX] Git Merge 예외처리
  main.js
Labels: fix

#49 [FIX] VCS Branch 기능 관련 개선사항
  main.js
  preload.js
  src/index.html
Labels: fix

#50 [DOC] Project README.md 문서 업데이트
  README.md
  README_Assets/Proj2_1.png
  README_Assets/Proj2_10.png
  README_Assets/Proj2_11.png
  README_Assets/Proj2_2.png
  README_Assets/Proj2_3.png
  README_Assets/Proj2_4.png
  README_Assets/Proj2_5.png
  README_Assets/Proj2_6.png
  README_Assets/Proj2_7.png
  README_Assets/Proj2_8.png
  README_Assets/Proj2_9.png
  Rules.md
Labels: documentation
